### ISSUE TITLE
When will be full release with tag?

### ISSUE THREAD

**Issue by kyrychenko-dmytro** [web3-php/web3#16]
When will be full release with tag? And will there be personal implementation (create account, unlock)?

**Comment by nunomaduro** [comment]
> When will be full release with tag? 

We don't know.

> And will there be personal implementation

Yes.

**Comment by kyrychenko-dmytro** [comment]
> Yes.

It's brilliant.

> We don't know.

Ok, try to use other package, but they almost all very bad(

**Comment by nunomaduro** [comment]
@kyrychenko-dmytro You can always choose to contribute to this package. Here are a few contributions that may help you to get started: https://github.com/web3-php/web3/pulls?q=is%3Apr+is%3Aclosed.

**Comment by kyrychenko-dmytro** [comment]
Ok, maybe my qualification is enough:)
