### ISSUE TITLE
Remove the final keyword so we can extend the classes

### ISSUE THREAD

**Issue by genesiscz** [web3-php/web3#19]
I would like to extend the Eth class to implement eth_call for example, but I am unable to do so because the class is final. The same applies to Web3 or even Http (I had to add Content-type into headers for my BSC RPC to work)

```
        $request = new Request('POST', $this->url, [
            "Content-Type" => "application/json",
        ], $body);
```

Could you consider removing the final keyword from them?

**Comment by owenvoke** [comment]
@genesiscz, would you be happy with adding `eth_call` to here directly as a PR? 🙂

**Comment by genesiscz** [comment]
I could, but it would require a lot more work because of the transaction needed to be signed (by your private key) which is definitely not a thing I can possibly do in an elegant correct way since I don't know the protocol goodly enough.

**Comment by nunomaduro** [comment]
Thank you for reporting this issue. What do you think about a solution that don't relies on inheritance? Do you have any ideas?

**Comment by owenvoke** [comment]
Think we might be able to solve this (in-part) by adding support for the `data` attribute to the `Transaction` object. Then just add an `eth_call` method which submits that. 🤷🏻

**Comment by genesiscz** [comment]
> Thank you for reporting this issue. What do you think about a solution that don't relies on inheritance? Do you have any ideas?

I guess there could be a per-method class which COULD be but DOESN'T HAVE TO be called via __call?

**Comment by genesiscz** [comment]
> Thank you for reporting this issue. What do you think about a solution that don't relies on inheritance? Do you have any ideas?

For example $transporter->call(new Eth_Call(.....));

**Comment by nunomaduro** [comment]
Feel free to pull request something here. We have no plans to remove the `final` keyword.
