### ISSUE TITLE
Invalid content type, only application/json is supported

### ISSUE THREAD

**Issue by lotfio** [web3-php/web3#22]
**Platform : windows 10
Php        : 8.0.13
Geth      : 1.10.14-stable** 

Trying to fetch eth accounts results in an invalid **null** `$response` passed to `array_key_exists` at `src\Transporters\Http.php:55`

![image](https://user-images.githubusercontent.com/18489496/148353879-15a4e298-3196-4ac8-b036-eb063f0632b1.png)

Debuging the contents of the http response shows a string  `Invalid content type, only application/json is supported`

![image](https://user-images.githubusercontent.com/18489496/148353712-bf40258d-64a9-4ba9-828e-8139e81fa89b.png)

Adding a content type to the request header fixes the issue 

![image](https://user-images.githubusercontent.com/18489496/148354364-4706f39c-b3b6-4640-ba56-f7b7b3f85356.png)

@nunomaduro  Let me know if i can help fixing the issue and make a PR !
cheers,

**Comment by nunomaduro** [comment]
Fixed.
