### ISSUE TITLE
Transaction input field

### ISSUE THREAD

**Issue by frmiqueias** [web3-php/web3#24]
How can I decode the transaction input field to get contract information, such as sent amount and also the recipient address.

**Comment by nunomaduro** [comment]
We are not sure. Feel free to pull request documentation or code that clarifies that.

**Comment by frmiqueias** [comment]
I use this Python tutorial to understand which stream to decode. https://medium.com/coinmonks/unlocking-the-secrets-of-an-ethereum-transaction-3a33991f696c

Also use some resources from this class https://github.com/CatAndPigeons/ethereum-adapter/blob/17b34c89976e1606904e64f97524280a8cf0ba50/src/Connector/EthereumRpcServiceTrait.php

So I created a Trait with a decodeInput method to decode ERC20 or BEP20 transfer transaction.

Thanks
