### ISSUE TITLE
How can I help?

### ISSUE THREAD

**Issue by adibhanna** [web3-php/web3#28]
Hey! Excuse me for using issues to try to connect.
I'd like to help with this project, do you have plans for what you'd like to add to it? 
Cheers!

**Comment by owenvoke** [comment]
If you find any methods that we've missed, feel free to open a pull request with those.

I think Nuno mentioned previously about supporting other chains other than EVM, I wonder if we could implement this easily. Perhaps by adding something in here like:

```php
public function solana(): Solana
{
    if (! class_exists(Solana::class)) {
        throw new DriverNotInstalled(Solana::class);
    }

    return new Solana($this);
}
```

Or something like that, that way we could have packages such as `web3-php/solana` that can be required.

Not sure what Nuno is wanting to be done with this. I know we were also thinking about a Laravel package, but haven't seen much happen with that.

**Comment by nunomaduro** [comment]
I would love to have `$web3->eth()->` or `$web3->sol()->`, or the missing methods of `eth` implemented. So fell free to contribute on that.
